"""
Given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string, if it is generated by deleting some characters of a given string without changing its order.

A string is called palindrome if is one that reads the same backward as well as forward.

Input: s = "ababa"
Output: 1
Explanation: String is already palindrome
"""


def removePalindromeSub(s):
    if len(s) == 0:
        return 0
    left = 0
    right = len(s) - 1

    while left < right:
        if s[left] != s[right]:
            return 2
        left += 1
        right -= 1
    return 1


s = "carerac"
print(removePalindromeSub(s))
