name: Run Pytest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  runsPytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: pip install pytest
      - run: python -m pytest Projects/GameOfLife/tests/
